# Generated by Django 3.2.4 on 2021-12-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
